import random
import struct

# Creates 100 points of real data (real value random, imaginary value 0)
with open("input.txt", "w") as f:
    for _ in range(100):
        inr_0 = random.uniform(-1e10, 1e10)
        ini_0 = 0
        inr_1 = random.uniform(-1e10, 1e10)
        ini_1 = 0
        inr_2 = random.uniform(-1e10, 1e10)
        ini_2 = 0
        inr_3 = random.uniform(-1e10, 1e10)
        ini_3 = 0
        inr_4 = random.uniform(-1e10, 1e10)
        ini_4 = 0
        inr_5 = random.uniform(-1e10, 1e10)
        ini_5 = 0
        inr_6 = random.uniform(-1e10, 1e10)
        ini_6 = 0
        inr_7 = random.uniform(-1e10, 1e10)
        ini_7 = 0
        inr_8 = random.uniform(-1e10, 1e10)
        ini_8 = 0
        inr_9 = random.uniform(-1e10, 1e10)
        ini_9 = 0
        inr_10 = random.uniform(-1e10, 1e10)
        ini_10 = 0
        inr_11 = random.uniform(-1e10, 1e10)
        ini_11 = 0
        inr_12 = random.uniform(-1e10, 1e10)
        ini_12 = 0
        inr_13 = random.uniform(-1e10, 1e10)
        ini_13 = 0
        inr_14 = random.uniform(-1e10, 1e10)
        ini_14 = 0
        inr_15 = random.uniform(-1e10, 1e10)
        ini_15 = 0
        inr_16 = random.uniform(-1e10, 1e10)
        ini_16 = 0
        inr_17 = random.uniform(-1e10, 1e10)
        ini_17 = 0
        inr_18 = random.uniform(-1e10, 1e10)
        ini_18 = 0
        inr_19 = random.uniform(-1e10, 1e10)
        ini_19 = 0
        inr_20 = random.uniform(-1e10, 1e10)
        ini_20 = 0
        inr_21 = random.uniform(-1e10, 1e10)
        ini_21 = 0
        inr_22 = random.uniform(-1e10, 1e10)
        ini_22 = 0
        inr_23 = random.uniform(-1e10, 1e10)
        ini_23 = 0
        inr_24 = random.uniform(-1e10, 1e10)
        ini_24 = 0
        inr_25 = random.uniform(-1e10, 1e10)
        ini_25 = 0
        inr_26 = random.uniform(-1e10, 1e10)
        ini_26 = 0
        inr_27 = random.uniform(-1e10, 1e10)
        ini_27 = 0
        inr_28 = random.uniform(-1e10, 1e10)
        ini_28 = 0
        inr_29 = random.uniform(-1e10, 1e10)
        ini_29 = 0
        inr_30 = random.uniform(-1e10, 1e10)
        ini_30 = 0
        inr_31 = random.uniform(-1e10, 1e10)
        ini_31 = 0

        inr_0_packed = struct.pack('>d', inr_0) 
        ini_0_packed = struct.pack('>d', ini_0) 
        inr_1_packed = struct.pack('>d', inr_1) 
        ini_1_packed = struct.pack('>d', ini_1) 
        inr_2_packed = struct.pack('>d', inr_2) 
        ini_2_packed = struct.pack('>d', ini_2) 
        inr_3_packed = struct.pack('>d', inr_3) 
        ini_3_packed = struct.pack('>d', ini_3) 
        inr_4_packed = struct.pack('>d', inr_4) 
        ini_4_packed = struct.pack('>d', ini_4) 
        inr_5_packed = struct.pack('>d', inr_5) 
        ini_5_packed = struct.pack('>d', ini_5) 
        inr_6_packed = struct.pack('>d', inr_6) 
        ini_6_packed = struct.pack('>d', ini_6) 
        inr_7_packed = struct.pack('>d', inr_7) 
        ini_7_packed = struct.pack('>d', ini_7) 
        inr_8_packed = struct.pack('>d', inr_8) 
        ini_8_packed = struct.pack('>d', ini_8) 
        inr_9_packed = struct.pack('>d', inr_9) 
        ini_9_packed = struct.pack('>d', ini_9) 
        inr_10_packed = struct.pack('>d', inr_10)
        ini_10_packed = struct.pack('>d', ini_10)
        inr_11_packed = struct.pack('>d', inr_11)
        ini_11_packed = struct.pack('>d', ini_11)
        inr_12_packed = struct.pack('>d', inr_12)
        ini_12_packed = struct.pack('>d', ini_12)
        inr_13_packed = struct.pack('>d', inr_13)
        ini_13_packed = struct.pack('>d', ini_13)
        inr_14_packed = struct.pack('>d', inr_14)
        ini_14_packed = struct.pack('>d', ini_14)
        inr_15_packed = struct.pack('>d', inr_15)
        ini_15_packed = struct.pack('>d', ini_15)
        inr_16_packed = struct.pack('>d', inr_16)
        ini_16_packed = struct.pack('>d', ini_16)
        inr_17_packed = struct.pack('>d', inr_17)
        ini_17_packed = struct.pack('>d', ini_17)
        inr_18_packed = struct.pack('>d', inr_18)
        ini_18_packed = struct.pack('>d', ini_18)
        inr_19_packed = struct.pack('>d', inr_19)
        ini_19_packed = struct.pack('>d', ini_19)
        inr_20_packed = struct.pack('>d', inr_20)
        ini_20_packed = struct.pack('>d', ini_20)
        inr_21_packed = struct.pack('>d', inr_21)
        ini_21_packed = struct.pack('>d', ini_21)
        inr_22_packed = struct.pack('>d', inr_22)
        ini_22_packed = struct.pack('>d', ini_22)
        inr_23_packed = struct.pack('>d', inr_23)
        ini_23_packed = struct.pack('>d', ini_23)
        inr_24_packed = struct.pack('>d', inr_24)
        ini_24_packed = struct.pack('>d', ini_24)
        inr_25_packed = struct.pack('>d', inr_25)
        ini_25_packed = struct.pack('>d', ini_25)
        inr_26_packed = struct.pack('>d', inr_26)
        ini_26_packed = struct.pack('>d', ini_26)
        inr_27_packed = struct.pack('>d', inr_27)
        ini_27_packed = struct.pack('>d', ini_27)
        inr_28_packed = struct.pack('>d', inr_28)
        ini_28_packed = struct.pack('>d', ini_28)
        inr_29_packed = struct.pack('>d', inr_29)
        ini_29_packed = struct.pack('>d', ini_29)
        inr_30_packed = struct.pack('>d', inr_30)
        ini_30_packed = struct.pack('>d', ini_30)
        inr_31_packed = struct.pack('>d', inr_31)
        ini_31_packed = struct.pack('>d', ini_31)

        inr_0_hex = inr_0_packed.hex()
        ini_0_hex = ini_0_packed.hex()
        inr_1_hex = inr_1_packed.hex()
        ini_1_hex = ini_1_packed.hex()
        inr_2_hex = inr_2_packed.hex()
        ini_2_hex = ini_2_packed.hex()
        inr_3_hex = inr_3_packed.hex()
        ini_3_hex = ini_3_packed.hex()
        inr_4_hex = inr_4_packed.hex()
        ini_4_hex = ini_4_packed.hex()
        inr_5_hex = inr_5_packed.hex()
        ini_5_hex = ini_5_packed.hex()
        inr_6_hex = inr_6_packed.hex()
        ini_6_hex = ini_6_packed.hex()
        inr_7_hex = inr_7_packed.hex()
        ini_7_hex = ini_7_packed.hex()
        inr_8_hex = inr_8_packed.hex()
        ini_8_hex = ini_8_packed.hex()
        inr_9_hex = inr_9_packed.hex()
        ini_9_hex = ini_9_packed.hex()
        inr_10_hex = inr_10_packed.hex()
        ini_10_hex = ini_10_packed.hex()
        inr_11_hex = inr_11_packed.hex()
        ini_11_hex = ini_11_packed.hex()
        inr_12_hex = inr_12_packed.hex()
        ini_12_hex = ini_12_packed.hex()
        inr_13_hex = inr_13_packed.hex()
        ini_13_hex = ini_13_packed.hex()
        inr_14_hex = inr_14_packed.hex()
        ini_14_hex = ini_14_packed.hex()
        inr_15_hex = inr_15_packed.hex()
        ini_15_hex = ini_15_packed.hex()
        inr_16_hex = inr_16_packed.hex()
        ini_16_hex = ini_16_packed.hex()
        inr_17_hex = inr_17_packed.hex()
        ini_17_hex = ini_17_packed.hex()
        inr_18_hex = inr_18_packed.hex()
        ini_18_hex = ini_18_packed.hex()
        inr_19_hex = inr_19_packed.hex()
        ini_19_hex = ini_19_packed.hex()
        inr_20_hex = inr_20_packed.hex()
        ini_20_hex = ini_20_packed.hex()
        inr_21_hex = inr_21_packed.hex()
        ini_21_hex = ini_21_packed.hex()
        inr_22_hex = inr_22_packed.hex()
        ini_22_hex = ini_22_packed.hex()
        inr_23_hex = inr_23_packed.hex()
        ini_23_hex = ini_23_packed.hex()
        inr_24_hex = inr_24_packed.hex()
        ini_24_hex = ini_24_packed.hex()
        inr_25_hex = inr_25_packed.hex()
        ini_25_hex = ini_25_packed.hex()
        inr_26_hex = inr_26_packed.hex()
        ini_26_hex = ini_26_packed.hex()
        inr_27_hex = inr_27_packed.hex()
        ini_27_hex = ini_27_packed.hex()
        inr_28_hex = inr_28_packed.hex()
        ini_28_hex = ini_28_packed.hex()
        inr_29_hex = inr_29_packed.hex()
        ini_29_hex = ini_29_packed.hex()
        inr_30_hex = inr_30_packed.hex()
        ini_30_hex = ini_30_packed.hex()
        inr_31_hex = inr_31_packed.hex()
        ini_31_hex = ini_31_packed.hex()
            
        f.write(f"{inr_0_hex} {ini_0_hex} {inr_1_hex} {ini_1_hex} {inr_2_hex} {ini_2_hex} {inr_3_hex} {ini_3_hex} {inr_4_hex} {ini_4_hex} {inr_5_hex} {ini_5_hex} {inr_6_hex} {ini_6_hex} {inr_7_hex} {ini_7_hex} {inr_8_hex} {ini_8_hex} {inr_9_hex} {ini_9_hex} {inr_10_hex} {ini_10_hex} {inr_11_hex} {ini_11_hex} {inr_12_hex} {ini_12_hex} {inr_13_hex} {ini_13_hex} {inr_14_hex} {ini_14_hex} {inr_15_hex} {ini_15_hex} {inr_16_hex} {ini_16_hex} {inr_17_hex} {ini_17_hex} {inr_18_hex} {ini_18_hex} {inr_19_hex} {ini_19_hex} {inr_20_hex} {ini_20_hex} {inr_21_hex} {ini_21_hex} {inr_22_hex} {ini_22_hex} {inr_23_hex} {ini_23_hex} {inr_24_hex} {ini_24_hex} {inr_25_hex} {ini_25_hex} {inr_26_hex} {ini_26_hex} {inr_27_hex} {ini_27_hex} {inr_28_hex} {ini_28_hex} {inr_29_hex} {ini_29_hex} {inr_30_hex} {ini_30_hex} {inr_31_hex} {ini_31_hex} \n") 
